# Create a data set of county level area information (the area is in square kilometer)
states.names=paste(state_name$state,"tract10",sep=".")
data(list=states.names)
area.list=list()
for (i in 1:length(states.names)){
  temp.tract10=spTransform(get(states.names[i]),CRS("+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
  fipsArea=cbind(temp.tract10$fips,areaPoly(temp.tract10))
  fipsArea=as.data.frame(fipsArea,stringsAsFactors=FALSE)
  fipsArea$V3=as.numeric(fipsArea$V2)
  fipsArea$fips=substr(fipsArea$V1,1,5)
  area.list[[i]]=aggregate(V3~fips,fipsArea,sum)
  print(i)
  rm(temp.tract10,fipsArea)
}
fipsArea=do.call("rbind",area.list)
rm(area.list)
names(fipsArea)=c("fips","area")
fipsArea$area=round(fipsArea$area/1e6,digits=1)
write.csv(fipsArea,"fipsArea.csv",row.names = F)
